package cn.vote.model;

// Generated 2014-6-29 1:14:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Voteinfo generated by hbm2java
 */
@Entity
@Table(name = "voteinfo", catalog = "vote")
public class Voteinfo implements java.io.Serializable {

	private Integer id;
	private Voteitem voteitem;
	private Users users;
	private Character usertype;
	private String votetime;
	private String votemark;

	public Voteinfo() {
	}

	public Voteinfo(Voteitem voteitem, String votetime) {
		this.voteitem = voteitem;
		this.votetime = votetime;
	}

	public Voteinfo(Voteitem voteitem, Users users, Character usertype,
			String votetime, String votemark) {
		this.voteitem = voteitem;
		this.users = users;
		this.usertype = usertype;
		this.votetime = votetime;
		this.votemark = votemark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemid", nullable = false)
	public Voteitem getVoteitem() {
		return this.voteitem;
	}

	public void setVoteitem(Voteitem voteitem) {
		this.voteitem = voteitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "usertype", length = 1)
	public Character getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Character usertype) {
		this.usertype = usertype;
	}

	@Column(name = "votetime", nullable = false, length = 20)
	public String getVotetime() {
		return this.votetime;
	}

	public void setVotetime(String votetime) {
		this.votetime = votetime;
	}

	@Column(name = "votemark", length = 100)
	public String getVotemark() {
		return this.votemark;
	}

	public void setVotemark(String votemark) {
		this.votemark = votemark;
	}

}
