package cn.vote.model;

// Generated 2014-6-29 1:14:17 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Votetheme generated by hbm2java
 */
@Entity
@Table(name = "votetheme", catalog = "vote")
public class Votetheme implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private char type;
	private Integer votemin;
	private Integer votemax;
	private String createtime;
	private String status;
	private Integer votenum;
	private List<Voteitem> voteitems = new ArrayList<Voteitem>(0);

	public Votetheme() {
	}

	public Votetheme(String title, String content, char type,
			String createtime, String status) {
		this.title = title;
		this.content = content;
		this.type = type;
		this.createtime = createtime;
		this.status = status;
	}

	public Votetheme(String title, String content, char type, Integer votemin,
			Integer votemax, String createtime, String status,
			List<Voteitem> voteitems) {
		this.title = title;
		this.content = content;
		this.type = type;
		this.votemin = votemin;
		this.votemax = votemax;
		this.createtime = createtime;
		this.status = status;
		this.voteitems = voteitems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", nullable = true, length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Column(name = "votemin")
	public Integer getVotemin() {
		return this.votemin;
	}

	public void setVotemin(Integer votemin) {
		this.votemin = votemin;
	}

	@Column(name = "votemax")
	public Integer getVotemax() {
		return this.votemax;
	}

	public void setVotemax(Integer votemax) {
		this.votemax = votemax;
	}

	@Column(name = "createtime", nullable = false, length = 20)
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}
	

	public void setStatus(String status) {
		this.status = status;
	}
	
	
	@Column(name = "votenum")
	public Integer getVotenum() {
		return votenum;
	}

	public void setVotenum(Integer votenum) {
		this.votenum = votenum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "votetheme")
	public List<Voteitem> getVoteitems() {
		return this.voteitems;
	}

	public void setVoteitems(List<Voteitem> voteitems) {
		this.voteitems = voteitems;
	}
	

}
